### ISSUE TITLE
SSL certificate for the thesharegame.com not renewed

### ISSUE THREAD

**Issue by jontze** [Zarathustra2/TheShareGame#42]
The ssl certificate for the domain thesharegame.com is not renewed and expired on 12.05.2021.

It looks like the certbot container failed again to renew.

### Screenshot
![image](https://user-images.githubusercontent.com/42588836/118353865-a090c300-b568-11eb-9ed2-88d87ca678c0.png)

# Reproduce
1. Visit www.thesharegame.com

### What did you expect to see?
The website

### What did you see instead?
A browser warning that the site is not secure and the ssl certificate is expired.

**Comment by Zarathustra2** [comment]
Fixed, thanks
