### ISSUE TITLE
Frontend: No Chat feedback

### ISSUE THREAD

**Issue by fneitzel** [Zarathustra2/TheShareGame#6]
Attempting to send a chat message on any company page as a not logged in user ends up in no response when clicking `save`

![image](https://user-images.githubusercontent.com/10213803/80894461-5fba6900-8cdb-11ea-84f3-083d22b30042.png)

Some feedback, that one is not allowed to participate in the chat or an anonymous message post would be appreciated.

**Comment by Zarathustra2** [comment]
Yes probably displaying a [toast](https://bootstrap-vue.org/docs/components/toast#toasts-on-demand) is the best call.
